build:
  tags:
    - build
  image: docker/compose:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - docker login -u babajack -p e@pQ9#Kb5ch@_xh
  script:
    - docker-compose build
    - docker-compose push
