build:
  tags:
    - build
  image: docker/compose:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker-compose build
    - docker-compose push
