version: '3.9'

services:

  node-docker:
    image: node-docker
    build: 
      context: ./backend/test-env
      dockerfile: ./Dockerfile
    command: ""

  node-backend:
    image: node-backend
    build:
      context: ./backend/node-express
      dockerfile: ./Dockerfile
      target: base
    volumes:
      - ./backend/node-express/src:/home/node/app/src
      - ./backend/node-express/nodemon.json:/home/node/app/nodemon.json
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: node-backend-docker
    expose:
      - '8000'
    ports:
      - '8000:8000'
    command: npm run dev