version: '3.7'

services:
  node-backend:
    image: node-backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: node-backend-docker
    expose:
      - '8000'
    ports:
      - '8000:8000'
    command: npm run dev