version: '3.7'

services:
  node-backend:
    image: node-backend
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    build:
      context: .
      dockerfile: ./Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - /usr/local/bin/docker:/usr/bin/docker
    container_name: node-backend-docker
    expose:
      - '8000'
    ports:
      - '8000:8000'
    command: npm run dev